[pytest]
testpaths = tests
addopts = -v  --alluredir=reports/allure-results --clean-alluredir

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    order: order tests